/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'siteStatus' : SiteStatus,
  'assignedEmployeeId' : [] | [bigint],
  'totalAmount' : number,
  'address' : string,
  'systemSizeKW' : number,
  'phone' : string,
  'amountReceived' : number,
}
export interface DashboardStats {
  'pendingSites' : bigint,
  'inProgressSites' : bigint,
  'totalAmountReceived' : number,
  'completedSites' : bigint,
  'totalCustomers' : bigint,
  'todayTasksCount' : bigint,
  'totalAmountPending' : number,
}
export interface Employee {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : EmployeeRole,
  'phone' : string,
}
export type EmployeeRole = { 'manager' : null } |
  { 'marketManager' : null } |
  { 'marketingStaff' : null } |
  { 'telecaller' : null } |
  { 'fieldWorker' : null };
export type SiteStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : string,
  'description' : string,
  'assignedEmployeeId' : [] | [bigint],
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<
    [string, string, string, number, number, number, SiteStatus, [] | [bigint]],
    bigint
  >,
  'createEmployee' : ActorMethod<[string, string, EmployeeRole], bigint>,
  'createTask' : ActorMethod<
    [string, string, [] | [bigint], TaskStatus, string],
    bigint
  >,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getDashboardStats' : ActorMethod<[string], DashboardStats>,
  'getEmployee' : ActorMethod<[bigint], Employee>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      number,
      number,
      SiteStatus,
      [] | [bigint],
    ],
    undefined
  >,
  'updateEmployee' : ActorMethod<
    [bigint, string, string, EmployeeRole],
    undefined
  >,
  'updateTask' : ActorMethod<
    [bigint, string, string, [] | [bigint], TaskStatus, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];