/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SiteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const EmployeeRole = IDL.Variant({
  'manager' : IDL.Null,
  'marketManager' : IDL.Null,
  'marketingStaff' : IDL.Null,
  'telecaller' : IDL.Null,
  'fieldWorker' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'siteStatus' : SiteStatus,
  'assignedEmployeeId' : IDL.Opt(IDL.Nat),
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'systemSizeKW' : IDL.Float64,
  'phone' : IDL.Text,
  'amountReceived' : IDL.Float64,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : EmployeeRole,
  'phone' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'assignedEmployeeId' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'pendingSites' : IDL.Nat,
  'inProgressSites' : IDL.Nat,
  'totalAmountReceived' : IDL.Float64,
  'completedSites' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
  'todayTasksCount' : IDL.Nat,
  'totalAmountPending' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        SiteStatus,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'createEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, EmployeeRole],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), TaskStatus, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [Employee], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        SiteStatus,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, EmployeeRole],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), TaskStatus, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SiteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const EmployeeRole = IDL.Variant({
    'manager' : IDL.Null,
    'marketManager' : IDL.Null,
    'marketingStaff' : IDL.Null,
    'telecaller' : IDL.Null,
    'fieldWorker' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'siteStatus' : SiteStatus,
    'assignedEmployeeId' : IDL.Opt(IDL.Nat),
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'systemSizeKW' : IDL.Float64,
    'phone' : IDL.Text,
    'amountReceived' : IDL.Float64,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : EmployeeRole,
    'phone' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'assignedEmployeeId' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'pendingSites' : IDL.Nat,
    'inProgressSites' : IDL.Nat,
    'totalAmountReceived' : IDL.Float64,
    'completedSites' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
    'todayTasksCount' : IDL.Nat,
    'totalAmountPending' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          SiteStatus,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'createEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, EmployeeRole],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), TaskStatus, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [Employee], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          SiteStatus,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, EmployeeRole],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), TaskStatus, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };